{% set name = "fast-bss-eval" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fast_bss_eval-{{ version }}.tar.gz
  sha256: b9b1307577f77128dda9efb8310ff4d4ca39afc0fccce0c62640a1e34f9add13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }},<4.0
    - scipy

test:
  imports:
    - fast_bss_eval
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fakufaku/fast_bss_eval
  summary: Package for fast computation of BSS Eval metrics for source separation
  description: |
    fast_bss_eval is a fast implementation of the bss_eval metrics for the evaluation of blind source separation. Our implementation of the bss_eval metrics has the several advantages compared to other existing ones.
  dev_url: https://github.com/fakufaku/fast_bss_eval/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wietsedv
